spring:
  datasource:
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - /js/**
            - /css/**
server:
  port: ${core.http.port}
  tomcat:
    remote-ip-header: X-Forwarded-For
    protocol-header: X-Forwarded-Proto
  servlet:
    session:
      persistent: true
      store-dir: ${java.io.tmpdir}/eoj-core-session
      timeout: 1d
  use-forward-headers: true
